import { StyleSheet } from "react-native";

export const applicationFormScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 8,
  },
  formContainer: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  stickyHeader: {
    marginHorizontal: -16,
    marginTop: -16,
    marginBottom: 4,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  stickyHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  stickyHeaderRightRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  stickyHeaderTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111827",
    flexShrink: 1,
  },
  statusCapsule: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#f9fafb",
  },
  statusCapsuleText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#374151",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginTop: 8,
  },
  dashedHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  dashedHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#9ca3af",
  },
  dashedHeaderText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#374151",
  },
  descriptionBox: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  descriptionText: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 21,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginTop: 4,
  },
  requiredAsterisk: {
    color: "#dc2626",
    fontWeight: "700",
  },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputError: {
    borderColor: "#dc2626",
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  countryCodeButton: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minWidth: 72,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  countryCodeText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
  },
  contactInput: {
    flex: 1,
  },
  textArea: {
    minHeight: 120,
  },
  helperMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: -2,
  },
  characterCounter: {
    fontSize: 12,
    color: "#6b7280",
    textAlign: "right",
  },
  helperErrorText: {
    color: "#dc2626",
    fontSize: 12,
    flex: 1,
  },
  helperHintText: {
    color: "#6b7280",
    fontSize: 12,
    flex: 1,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionsContainer: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  submitButtonWrap: {
    flex: 1,
  },
  deleteButton: {
    backgroundColor: "#ef4444",
  },
  countryPickerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17, 24, 39, 0.45)",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  countryPickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 8,
  },
  countryPickerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 2,
  },
  countryPickerOptionsList: {
    maxHeight: 360,
  },
  countryPickerOptionsContent: {
    gap: 8,
    paddingBottom: 2,
  },
  countryPickerOption: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  countryPickerOptionText: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "500",
  },
});
